# Generated by Django 5.1 on 2024-08-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('mail_admin', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChambreClimatisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='document/chambres_climatisees/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChambreVentilee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='document/chambres_ventilees/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='document/espaces/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_depot', models.CharField(max_length=20)),
                ('capture_depot', models.ImageField(upload_to='document/paiements/')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='document/suites/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/suites/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/suites/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/suites/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('mail_admin', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambre_climatisee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambreclimatisee')),
                ('chambre_ventilee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambreventilee')),
                ('suite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.suite')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacter', models.CharField(max_length=20)),
                ('date_arriver', models.DateField()),
                ('heure_arriver', models.TimeField()),
                ('temps_sejour', models.IntegerField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeEspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacter', models.CharField(max_length=20)),
                ('date_arriver', models.DateField()),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.espace')),
            ],
        ),
    ]
