# Generated by Django 4.2.16 on 2024-09-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('mail_admin', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutChambre', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChambreClimatisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroChambre', models.CharField(max_length=10, unique=True)),
                ('photo1', models.ImageField(upload_to='document/chambres_climatisees/images/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/images/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/images/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/images/')),
                ('video1', models.FileField(upload_to='document/chambres_climatisees/videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='document/chambres_climatisees/videos/')),
                ('video3', models.FileField(blank=True, null=True, upload_to='document/chambres_climatisees/videos/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutChambre', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChambreVentilee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroChambre', models.CharField(max_length=10, unique=True)),
                ('photo1', models.ImageField(upload_to='document/chambres_ventilees/images/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/images/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/images/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/images/')),
                ('video1', models.FileField(upload_to='document/chambres_ventilees/videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='document/chambres_ventilees/videos/')),
                ('video3', models.FileField(blank=True, null=True, upload_to='document/chambres_ventilees/videos/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutChambre', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='document/espaces/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='document/espaces/')),
                ('description', models.TextField()),
                ('descriptionSalleReception', models.TextField(blank=True, null=True)),
                ('descriptionSalleVip', models.TextField(blank=True, null=True)),
                ('descriptionGarage', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroChambre', models.CharField(max_length=10, unique=True)),
                ('photo1', models.ImageField(upload_to='document/suites/images/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='document/suites/images/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='document/suites/images/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='document/suites/images/')),
                ('video1', models.FileField(upload_to='document/suites/videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='document/suites/videos/')),
                ('video3', models.FileField(blank=True, null=True, upload_to='document/suites/videos/')),
                ('description', models.TextField()),
                ('prix_nuite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutChambre', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('mail_utilisateur', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacter', models.CharField(max_length=20)),
                ('date_arriver', models.DateField()),
                ('heure_arriver', models.TimeField()),
                ('temps_sejour', models.IntegerField()),
                ('choixSejour', models.CharField(blank=True, max_length=20, null=True)),
                ('total_a_payer', models.CharField(max_length=50)),
                ('etat_commande', models.CharField(choices=[('validee', 'Commande validée'), ('refusee', 'Commande refusée'), ('en_attente', 'En attente')], default='en_attente', max_length=10)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambre')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeEspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacter', models.CharField(max_length=20)),
                ('date_arriver', models.DateField()),
                ('etat_commande', models.CharField(choices=[('validee', 'Commande validée'), ('refusee', 'Commande refusée'), ('en_attente', 'En attente')], default='en_attente', max_length=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.espace')),
            ],
        ),
        migrations.CreateModel(
            name='CodeRecuperationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CodeConnexionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.administrateur')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='chambre_climatisee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambreclimatisee'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='chambre_ventilee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.chambreventilee'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='suite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.suite'),
        ),
    ]
