# Generated by Django 4.2.16 on 2024-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espace',
            name='statutEspace',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10),
        ),
    ]
