# Generated by Django 5.1 on 2024-08-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mail_admin',
            new_name='mail_utilisateur',
        ),
    ]
