# Generated by Django 5.1 on 2024-09-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_rename_mail_admin_utilisateur_mail_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
