# Generated by Django 3.1.6 on 2024-08-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_rename_mail_admin_utilisateur_mail_utilisateur'),
        ('utilisateur', '0002_auto_20240830_0049'),
    ]

    operations = [
    ]
