# Generated by Django 5.1 on 2024-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_codeconnexionadmin_coderecuperationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espace',
            name='numeroChambre',
        ),
        migrations.AddField(
            model_name='espace',
            name='descriptionGarage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espace',
            name='descriptionSalleReception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espace',
            name='descriptionSalleVip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
