# Generated by Django 5.1 on 2024-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_remove_espace_numerochambre_espace_descriptiongarage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandelogement',
            name='total_a_payer',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
