# Generated by Django 5.1 on 2024-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_commandelogement_total_a_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeespace',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
