# Generated by Django 5.1 on 2024-09-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_commandeespace_nom_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeespace',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
        migrations.AddField(
            model_name='commandelogement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
    ]
