# Generated by Django 5.1 on 2024-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_commandeespace_client_commandelogement_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambreclimatisee',
            name='statutChambre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chambreventilee',
            name='statutChambre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suite',
            name='statutChambre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='statutChambre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
