# Generated by Django 5.1 on 2024-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_chambreclimatisee_statutchambre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandelogement',
            name='choixSejour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
