# Generated by Django 5.1 on 2024-09-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_commandelogement_choixsejour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeespace',
            name='nom_complet',
        ),
    ]
