# Generated by Django 4.2.16 on 2024-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_remove_commandeespace_nom_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambreclimatisee',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='document/chambres_climatisees/images/'),
        ),
        migrations.AlterField(
            model_name='chambreclimatisee',
            name='statutChambre',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='chambreclimatisee',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='document/chambres_climatisees/videos/'),
        ),
    ]
