# Generated by Django 4.2.16 on 2024-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_alter_chambreclimatisee_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambreventilee',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='document/chambres_ventilees/images/'),
        ),
        migrations.AlterField(
            model_name='chambreventilee',
            name='statutChambre',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='chambreventilee',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='document/chambres_ventilees/videos/'),
        ),
        migrations.AlterField(
            model_name='espace',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='document/espaces/'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='document/suites/images/'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='statutChambre',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='suite',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='document/suites/videos/'),
        ),
    ]
